//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KutuphaneDBEntities : DbContext
    {
        public KutuphaneDBEntities()
            : base("name=KutuphaneDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_KITAPLAR> TBL_KITAPLAR { get; set; }
        public virtual DbSet<TBL_TURLER> TBL_TURLER { get; set; }
        public virtual DbSet<TBL_YAZARLAR> TBL_YAZARLAR { get; set; }
        public virtual DbSet<TBL_ALINACAK> TBL_ALINACAK { get; set; }
    
        public virtual ObjectResult<KitapBilgileri_Result> KitapBilgileri()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KitapBilgileri_Result>("KitapBilgileri");
        }
    
        public virtual ObjectResult<KitapListesi_Result> KitapListesi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KitapListesi_Result>("KitapListesi");
        }
    
        public virtual ObjectResult<Okuyucu_Result> Okuyucu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Okuyucu_Result>("Okuyucu");
        }
    
        public virtual ObjectResult<OkuyucuParm_Result> OkuyucuParm(Nullable<int> kULLANICIID)
        {
            var kULLANICIIDParameter = kULLANICIID.HasValue ?
                new ObjectParameter("KULLANICIID", kULLANICIID) :
                new ObjectParameter("KULLANICIID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OkuyucuParm_Result>("OkuyucuParm", kULLANICIIDParameter);
        }
    
        public virtual ObjectResult<HakaninKitaplari_Result> HakaninKitaplari()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HakaninKitaplari_Result>("HakaninKitaplari");
        }
    
        public virtual ObjectResult<HazelinKitaplari_Result> HazelinKitaplari()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HazelinKitaplari_Result>("HazelinKitaplari");
        }
    }
}
