//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_YAZARLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_YAZARLAR()
        {
            this.TBL_KITAPLAR = new HashSet<TBL_KITAPLAR>();
        }
    
        public int YAZARID { get; set; }
        public string YAZARADSOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_KITAPLAR> TBL_KITAPLAR { get; set; }
    }
}
