//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ALINACAK
    {
        public int ALKITAPID { get; set; }
        public string ALKITAPAD { get; set; }
    }
}
