//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KITAPLAR
    {
        public int KITAPID { get; set; }
        public string KITAPAD { get; set; }
        public Nullable<int> KITAPYAZARID { get; set; }
        public Nullable<int> KITAPTURID { get; set; }
        public Nullable<int> BASIMYILI { get; set; }
        public Nullable<int> SAYFASAYISI { get; set; }
        public Nullable<int> OKUYANID { get; set; }
    
        public virtual TBL_ADMIN TBL_ADMIN { get; set; }
        public virtual TBL_TURLER TBL_TURLER { get; set; }
        public virtual TBL_YAZARLAR TBL_YAZARLAR { get; set; }
    }
}
